_homepage:
    path: /
    defaults: { _controller: MwebCoreBundle:Default:index, _locale: fr }
    requirements:
        _locale: %locales%

circa_page:
  path: /festival/{slug}
  defaults: { _controller: MwebCoreBundle:Default:page, _locale: fr }

circa_news:
  path: /actu/{slugNews}
  defaults: { _controller: MwebCoreBundle:Default:news, _locale: fr }