mwebadmin:
    prefix: /admin/
    resource: "@MwebAdminBundle/Resources/config/routing.yml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

mweb:
    resource: "@MwebCoreBundle/Resources/config/routing.yml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
